export { default as Footer} from './footer/Footer'
export { default as Header} from './header/Header'
export { default as NavBar} from './navbar/Navbar'
export { default as Review} from './review/Review'
export { default as WeWork} from './weWork/WeWork'
